### PR TITLE
A wildcard to exclude all generated headers from coverage

### PR DESCRIPTION
**Pull request by ct2034**
We have had this list of headers to exclude. It is cleaner this way. 
The only thing is that this also excludes some files that we previously tested (which were green). Is this a good idea? @hslusarek @agutenkunst @martiniil

### CODE REVIEW

**Comment by ct2034** [comment]
### before:
Screenshot from 2019-08-22 15-51-10

### after:
Screenshot from 2019-08-22 15-46-14

**Comment by hslusarek** [comment]
> We have had this list of headers to exclude. It is cleaner this way.
> The only thing is that this also excludes some files that we previously tested (which were green). Is this a good idea?

In my opinion all auto generated files can be excluded. Are files excluded which are implemented by us? If so, which ones?

**Comment by ct2034** [comment]
No. None were implemented by us. Can you please approve, then.

**Review by hslusarek — APPROVED** [review]

**Comment by ct2034** [comment]
another case of #230

**Pull request merged**
