### PR TITLE
Add linkprefix to ik solver plugin

### PR DESCRIPTION
**Pull request by jschleicher**
See ros-planning/moveit#1567

### CODE REVIEW

**Comment by ct2034** [comment]
isn't this part of the auto-generated code? Would it not make more sense to change is upstream in https://github.com/ros-planning/moveit/blob/master/moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp

**Comment by jschleicher** [comment]
The upstream PR is merged now. Plugin re-generated from moveit master (and force-pushed). This branch is based on  `feature/ikfast-without-lapack`, so #186 needs to be merged first (Then squash-merge this one?).

**Review by ct2034 — APPROVED** [review]

**Comment by ct2034** [comment]
@jschleicher can you please resolve the conflicts. Afterwards, you can merge it.

**Comment by jschleicher** [comment]
Cherry-picked and force-pushed the relevant commits. Merge if travis succeeds...

**Pull request merged**
