### PR TITLE
Add missing dependency on joint_state_controller

### PR DESCRIPTION
**Pull request by martiniil**
Also remove some redundant dependencies.

### CODE REVIEW

**Comment by jschleicher** [comment]
Why is `joint_trajectory_controller` redundant? prbt_support starts it in its controller config?! Do you want to move `joint_trajectory_controller` as `<run_depend>` into `prbt_hardware_support`?

**Review by jschleicher — CHANGES_REQUESTED** [review]
Please keep `joint_trajectory_controller` as dependency of prbt_support.

**Comment by martiniil** [comment]
@jschleicher thanks for your comments.
prbt_support starts the `pilz_joint_trajectory_controller` from the dependency `pilz_control` (which of course depends on `joint_trajectory_controller`). That's why I think it was redundant. What do you think?

**Comment by jschleicher** [comment]
Alright, I had a look into prbt_hardware support, but you're right. The controller part is inside pilz_control.

**Review by jschleicher — APPROVED** [review]

**Comment by jschleicher** [comment]
Maybe add a comment near the exec_depend of pilz_control.

**Pull request merged**
