### PR TITLE
add code coverage make target

### PR DESCRIPTION
**Pull request by jschleicher**
by introducing dependency on code_coverage package
See https://github.com/mikeferguson/code_coverage for documentation

### CODE REVIEW

**Comment by agutenkunst** [comment]
Currently this fails on my machine with:

```
Errors     << prbt_ikfast_manipulator_plugin:check /home/agutenkunst/catkin_ws/logs/prbt_ikfast_manipulator_plugin/build.check.004.log                                                                                                
CMake Error at /home/agutenkunst/catkin_ws/src/pilz_robots/prbt_ikfast_manipulator_plugin/CMakeLists.txt:63 (include):
  include could not find load file:

    CodeCoverage


CMake Error at /home/agutenkunst/catkin_ws/src/pilz_robots/prbt_ikfast_manipulator_plugin/CMakeLists.txt:64 (APPEND_COVERAGE_COMPILER_FLAGS):
  Unknown CMake command "APPEND_COVERAGE_COMPILER_FLAGS".


make: *** [cmake_check_build_system] Error 1

```

**Review by agutenkunst — CHANGES_REQUESTED** [review]
Currently this fails on my machine with:

```
Errors     << prbt_ikfast_manipulator_plugin:check /home/agutenkunst/catkin_ws/logs/prbt_ikfast_manipulator_plugin/build.check.004.log                                                                                                
CMake Error at /home/agutenkunst/catkin_ws/src/pilz_robots/prbt_ikfast_manipulator_plugin/CMakeLists.txt:63 (include):
  include could not find load file:

    CodeCoverage


CMake Error at /home/agutenkunst/catkin_ws/src/pilz_robots/prbt_ikfast_manipulator_plugin/CMakeLists.txt:64 (APPEND_COVERAGE_COMPILER_FLAGS):
  Unknown CMake command "APPEND_COVERAGE_COMPILER_FLAGS".


make: *** [cmake_check_build_system] Error 1

```

**Comment by jschleicher** [comment]
See upstream pull-request https://github.com/mikeferguson/code_coverage/pull/7

**Comment by jschleicher** [comment]
Please retry with upstream ros-kinetic-code-coverage version 0.2.3

**Review by agutenkunst — APPROVED** [review]

**Pull request merged**
