### PR TITLE
Fix type conversion by makeing timeout long

### PR DESCRIPTION
**Pull request by agutenkunst**
Needed for https://github.com/PilzDE/pilz_robots/pull/145

### CODE REVIEW

**Review by ct2034 — CHANGES_REQUESTED** [review]
Please add a pointer to where this method is used

**Comment by agutenkunst** [comment]
It is actually about the return value of getResponseTimeout()

https://github.com/PilzDE/pilz_robots/blob/a5f2b244923747dcaebf40ceeb75fcae5aa7a50d/prbt_hardware_support/src/libmodbus_client.cpp#L60

**Review by ct2034 — COMMENTED** [review]
but who uses it?

**Review by ct2034 — APPROVED** [review]
ok :+1:

**Pull request merged**
