### PR TITLE
Remove speed override service definition

### PR DESCRIPTION
**Pull request by leunMar**
Follow-up to PilzDE/pilz_industrial_motion#224

### CODE REVIEW

**Comment by jschleicher** [comment]
As said before: From my point-of-view: In customer eyes speed override should be a (latched!) topic, everyone interested can subscribe. Service calls are for short-living actions, like function calls for enabling something.

Please consider refactoring.

**Comment by leunMar** [comment]
@jschleicher See https://github.com/PilzDE/pilz_industrial_motion/pull/225#issuecomment-552330636.

**Review by HiddenBug — APPROVED** [review]
Looks good to me. Merge as soon as Travis-CI is green.

**Comment by HiddenBug** [comment]
> As said before: From my point-of-view: In customer eyes speed override should be a (latched!) topic, everyone interested can subscribe. Service calls are for short-living actions, like function calls for enabling something.
> 
> Please consider refactoring.

Please see my answer to your request:
https://github.com/PilzDE/pilz_industrial_motion/pull/224#issuecomment-554438522

**Pull request merged**
