### PR TITLE
Precised Runpermitted signal to match with PSS4000 naming

### PR DESCRIPTION
**Pull request by JonathanGruner**

### CODE REVIEW

**Comment by martiniil** [comment]
Changing an existing entry in the *.yaml* file without adapting the rest of the code doesn't work. But your change it is a worthy suggestion.

**Comment by JonathanGruner** [comment]
Ok I understand, but could you please discuss it in your team? 
Because in fact, the Run_Permitted signal isn't an STO signal - the STO signal is a 2 channel digital signal to the robot, and it comes sth about 340 ms after the "STO-Modbus-Signal" in your spec. 
Its not very high priority, but I would better change it now, when no applications are running, than change it in months, when all "customers" have to change their applications.

**Comment by agutenkunst** [comment]
Please consider opening a WIP Pull Request (https://github.blog/2019-02-14-introducing-draft-pull-requests/) or even open a Issue next time. Thank you!

**Comment by JonathanGruner** [comment]
Okay I will see if I am able to do that next time.

**Comment by JonathanGruner** [comment]
Hi,deine Kollegen meinten ich kann bei so kleinen dingen auch einfach ein pull request machen.Kann aber auch weiterhin issues machen.wie willst du es haben?lg,Jonathan-----"Alexander Gutenkunst" <notifications@github.com> schrieb: -----An: "PilzDE/pilz_robots" <pilz_robots@noreply.github.com>Von: "Alexander Gutenkunst" <notifications@github.com>Datum: 08.10.2019 06:16Kopie: "JonathanGruner" <j.gruner@pilz.de>, "Author" <author@noreply.github.com>Betreff: Re: [PilzDE/pilz_robots] Precised Runpermitted signal to match with PSS4000 naming (#256)Please consider opening a WIP Pull Request (https://github.blog/2019-02-14-introducing-draft-pull-requests/) or even open a Issue next time. Thank you!
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

Geschäftsführung: Susanne Kunschert, Thomas PilzPilz GmbH & Co. KG, Sitz: Ostfildern, HRA 210 893, Amtsgericht StuttgartKompl. Ges. Peter Pilz GmbH, Sitz: Ostfildern, HRB 210 612, Amtsgericht StuttgartUmsatzsteuer: ID-Nr. DE 145 355 773, WEEE-Reg.-Nr. DE 71636849This email is intended solely for the use of the named address(es). Any unauthorised disclosure, copying or distribution of these confidential information contained therein, or the taking of any action based on it, is prohibited. The sender disclaims any liability for the integrity of this email. Legally binding declarations must be in written form.Umweltschutz liegt uns am Herzen! - Bitte denken Sie an unsere Umwelt, bevor Sie diese E-Mail drucken.We do care about the environment! - Please consider the environment before printing this e-mail.

**Pull request closed without merging**
