### PR TITLE
Add Readme for pilz_testutils

### PR DESCRIPTION
**Pull request by martiniil**
More sample code is contained in the header file: `asyn_test.h`

- [x] edit ROS wiki

### CODE REVIEW

**Comment by martiniil** [comment]
Interestingly enough, there is already a docu available:
http://docs.ros.org/melodic/api/pilz_testutils/html/
This should not exist. Is this an error in the release configuration? Is this in our hands?

**Comment by agutenkunst** [comment]
Melodic doc job pulls from kinetic-devel

**Comment by jschleicher** [comment]
@agutenkunst Is the gazebo-tets-failure expected? Could you have a look at the travis log?

**Review by jschleicher — APPROVED** [review]
Good. Feel free to merge once Travis goes green.

**Comment by martiniil** [comment]
> @agutenkunst Is the gazebo-tets-failure expected? Could you have a look at the travis log?

See https://github.com/PilzDE/pilz_robots/pull/40

**Pull request merged**
