### PR TITLE
[pilz_status_indicator_rqt:] Hide currently unsupported ui elements. Fixes #435

### LINKED ISSUE #435: Status indicator GUI shows red icons
### Commit
9aa67f91c75c1fd240d0562a6ef31a49bb264db9 on melodic-devel

### Steps to reproduce
1. Start the ROS system as described in the [pilz_robots/README.md](https://github.com/PilzDE/pilz_robots/blob/melodic-devel/README.md#running-on-the-real-robot)
2. After start-up the status indicator GUI shows constantly red icons for ROS and the hardware:

status_indicator_error

### Observed behavior
- As a user I get easily confused by a GUI which constantly shows me that something is not okay.

### Expected behavior
- Maybe it would be better, if the feature is not supported, to deactivate this icons or at least to make them grey or something?

### PR DESCRIPTION
**Pull request by martiniil**
Snapshot:

status_indicator_elements_hidden

### CODE REVIEW

**Review by jschleicher — APPROVED** [review]
Thanks!

**Comment by agutenkunst** [comment]
Why is speed not working?

**Comment by martiniil** [comment]
> Why is speed not working?

The topic `/prbt/speed_override` is not implemented, see [architecture diagram](https://github.com/PilzDE/pilz_robots/blob/melodic-devel/prbt_hardware_support/doc/diag_comp_overall_architecture.png)

**Review by agutenkunst — APPROVED** [review]

**Comment by agutenkunst** [comment]
Approved

**Pull request merged**
