### PR TITLE
buildfarm badges

### PR DESCRIPTION
**Pull request by ct2034**
Adding badges to monitor buildfarm status in readme

### CODE REVIEW

**Review by agutenkunst — CHANGES_REQUESTED** [review]
I would write Buildfarm instead of BF

Or we could go the extra mile to have it like MoveIt! https://github.com/ros-planning/moveit

**Comment by ct2034** [comment]
please also review https://github.com/PilzDE/pilz_industrial_motion/pull/183

**Comment by ct2034** [comment]
> Or we could go the extra mile to have it like MoveIt! https://github.com/ros-planning/moveit

no. We would need a script for that. And for the script we would need a pbi-item

**Comment by agutenkunst** [comment]
OK.

**Review by agutenkunst — APPROVED** [review]

**Review by agutenkunst — APPROVED** [review]

**Pull request merged**
